### ISSUE TITLE
Server crash with latest client (in testbed)

### ISSUE THREAD

**Issue by kerneis-anssi** [ANSSI-FR/ultrablue#10]
When testing PR #7, I get the following error in the testbed, running the server in `--enroll` mode and the latest client on a Pixel 4a:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5dbce7]

goroutine 16 [running]:
main.parseAttestEK(0xc000136c30)
	/root/src/protocol.go:98 +0x1a7
main.registration(0xc000013860?, 0xc0000495d0)
	/root/src/protocol.go:115 +0x113
main.ultrablueProtocol(0xc0000a0480?)
	/root/src/protocol.go:250 +0xde
created by main.getConnectionState
	/root/src/state.go:95 +0x185
```

The last message I see on the Android side is ```Getting EkPub and EkCert```. 

This does not happen when running the server outside of the testbed. My guess is that this comes from the fact that I don't have clean build of the testbed, so my server and client are out-of-sync.

However, the server should not crash, even if the client sends garbage data. We should investigate this crash and makes sure the server handles the situation properly.

**Comment by ghost** [comment]
This is due to the fact that virtual TPMs does not ships EK certificate, and I din't checked for it.

**Comment by nbouchinet-anssi** [comment]
Please keep your mkosi.output somewhere so we can investigate this, is there a way you can send it to me ?

**Comment by kerneis-anssi** [comment]
Confirmed that it crashes even with a clean build.
